version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: insurance
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/insurance
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db-data:
